### ISSUE TITLE
Document website is down

### ISSUE THREAD

**Issue by mehrab-wj** [yepwoo/laragine#27]
Hi there, thanks for your effort to develop this package, but looks like your documentation website is down right now due to the PHP version.

URL: https://yepwoo.com/products/laragine/docs/v2/introduction
ERROR:  `Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".`

**Comment by AbdlrahmanSaberAbdo** [comment]
Hi @mehrab-wj, thank you for letting us know, It's working now please check it.
